### ISSUE TITLE
0.2.4_py_2 is being preferred over 0.2.6_py_1 when installing spyder

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/spyder-kernels-feedstock#18]
issuing `conda install spyder`

yields the following results:

```
The following NEW packages will be INSTALLED:
[...]
ipykernel:                4.9.0-py36_0           conda-forge
[...]
spyder-kernels:           0.2.6-py_0             conda-forge
```

The issue is that ipykernels 4.9.0 is broken on windows. This PR created a new build for spyder-kernels (build 1), which was supposed to take over:
https://github.com/conda-forge/spyder-kernels-feedstock/pull/16

but it isn't being found.

Accepting that spyder be installed then calling:
```
conda install spyder-kernels=0
```
finds build 1 as expected and downgrades ipykernel to 4.8.2

**Comment by ccordoba12** [comment]
@ocefpaf, @jakirkham, could you help us to remove [noarch/spyder-kernels-0.2.6-py_0.tar.bz2](https://anaconda.org/conda-forge/spyder-kernels/0.2.6/download/noarch/spyder-kernels-0.2.6-py_0.tar.bz2) to fix this?

This is out of our control because (as @hmaarrfk said) ipykernel 4.9.0 is broken on Windows and that version was skipped in build 1.

**Comment by ocefpaf** [comment]
Done. See https://anaconda.org/conda-forge/spyder-kernels/files?version=0.2.6

**Comment by hmaarrfk** [comment]
@ccordoba12 it seems now that `spyder-kernels:           0.2.4-py_2             conda-forge` is being preferred.

I guess blacklisting 4.9.0 isn't as easy as I thought :/

It seems to prefer downgrading bugfix versions for spyder-kernels than downgrade minor versions of `ipykernels`

**Comment by hmaarrfk** [comment]
This makes no sense. A recent build on travis (albeit osx) confirms that it pulls in the desired dependencies 
https://travis-ci.org/conda-forge/spyder-feedstock/jobs/433612337#L2668

**Comment by hmaarrfk** [comment]
Oh well. thanks for working on this guys, this is going to be moot when Appveyor finishes building 

https://github.com/conda-forge/ipykernel-feedstock/pull/30

**Comment by ccordoba12** [comment]
Finally!
