### ISSUE TITLE
Failure when trying to upload package to Anaconda.org

### ISSUE THREAD

**Issue by ccordoba12** [conda-forge/spyder-kernels-feedstock#21]
@conda-forge/core, I don't why packages for the latest release of `spyder-kernels` were not uploaded to anaconda.org

This is the reported error in Appveyor:

https://ci.appveyor.com/project/conda-forge/spyder-kernels-feedstock/builds/20525830/job/qyrxjbgt77eytp82

The one in Travis is exactly the same.

**Comment by jjhelmus** [comment]
Perhaps the Anaconda.org upload tokens have expired?  Any other @conda-forge/core member have insight into this?

**Comment by isuruf** [comment]
Apply the patch https://github.com/conda-forge/spyder-kernels-feedstock/commit/351689d2acaa5d93742d6819b5a0af480d6ec7fa on that branch and rerender
